#!/usr/bin/env sh
# sync-agents-md.sh
# Regenerates AGENTS.md from skills/mkv-cleaner/SKILL.md.
# Usage: ./scripts/sync-agents-md.sh [--check]

set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
SKILL="$ROOT/skills/mkv-cleaner/SKILL.md"
AGENTS="$ROOT/AGENTS.md"

if [ ! -f "$SKILL" ]; then
  echo "ERROR: not found: $SKILL" >&2
  exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "<!-- Generated by scripts/sync-agents-md.sh from skills/mkv-cleaner/SKILL.md. Edit the skill, not this file. -->"
  echo ""
  awk 'NR == 1 && $0 == "---" { infm = 1; next } infm && $0 == "---" { infm = 0; skip = 1; next } infm { next } skip { skip = 0; next } { print }' "$SKILL"
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if diff -u "$AGENTS" "$TMP"; then
    echo "AGENTS.md is in sync with SKILL.md"
    exit 0
  fi
  echo "" >&2
  echo "ERROR: AGENTS.md is out of sync. Run ./scripts/sync-agents-md.sh" >&2
  exit 1
fi

cp "$TMP" "$AGENTS"
echo "Wrote $AGENTS"
