#!/usr/bin/env bash
# sync-prompts.sh
# Syncs the canonical prompt to all tool-specific locations.
# Run this after editing prompts/mkv-cleaner.md, or let the pre-commit hook do it automatically.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE="$REPO_ROOT/prompts/mkv-cleaner.md"

HEADER="<!-- AUTO-GENERATED from prompts/mkv-cleaner.md — do not edit this file directly -->
<!-- Run scripts/sync-prompts.sh or commit via the pre-commit hook to regenerate -->
"

if [[ ! -f "$SOURCE" ]]; then
  echo "ERROR: Source file not found: $SOURCE" >&2
  exit 1
fi

sync_file() {
  local dest="$1"
  local dir
  dir="$(dirname "$dest")"
  mkdir -p "$dir"
  printf '%s\n' "$HEADER" > "$dest"
  cat "$SOURCE" >> "$dest"
  echo "  ✓ $dest"
}

echo "Syncing prompt from prompts/mkv-cleaner.md..."
sync_file "$REPO_ROOT/CLAUDE.md"
sync_file "$REPO_ROOT/AGENTS.md"
echo "Done."
